[package]
name = "lava-lamp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.22.0", features = ["rand"] }
rand = "0.8.5"
rustbox = "0.11.0"
